### ISSUE TITLE
Use of `b` method incorrectly includes a space before punctuation

### ISSUE THREAD

**Issue by simonvarey** [rali-udem/jsRealB#54]
A sentence like `S(Pro("I"), VP(V("be")).b(','))` is realized as "It , is." when it should be realized as "It, is". `S(Pro("I").a(','), VP(V("be")))` is realized correctly.

**Comment by lapalme** [comment]
I am not sure if this is a bug or a feature...  .b() in front of a VP should not be added at the end to the word before especially if it is not in the same Phrase.
 
Usually a comma is followed by a space and should be used in the context of a .a().

**Comment by simonvarey** [comment]
Maybe I should (roughly) discuss my use case: I have a sentence like `S` = 'I saw a cat on a mat' and I want to add either the non-restrictive clause `C1` = 'where she was sitting peacefully' or restrictive clause `C2` = 'with a tasseled border' as `S.add(C1)` or `S.add(C2)`.

The first should be realized as 'I saw a cat on a mat, where she was sitting peacefully' while the second should be realized as 'I saw a cat on a mat with a tasseled border'. I would like to be able to add the comma to `C1` and not `C2`, but doing so currently in JSRealB leads to the incorrect realization 'I saw a cat on a mat , where she was sitting peacefully'. Of course, I could realize this sentence as `S.a(',').add(C1)`, but then I would have to treat `C1` differently to `C2` which is not very ergonomic.

Perhaps is this more of a feature request than a bug, but as far as I can see the current behaviour is unlikely to be useful to anybody (and, if really needed, could be recreated through `.a(' ,')`), and I behaviour I have suggested here would be useful to me and I suspect others.

**Comment by lapalme** [comment]
Having looked a bit how this case could be "patched", I am a bit reluctant to try to take this into account because it would complicate the "detokenization" process which is now very systematic (separate each token with a space unless the next one starts with a space, dash or apostrophe). I am afraid that trying to take care of this would break other things. To deal with your use case, I suggest that you define a custom function that depending of the type of clause would add .a(",") or not and then .add(Ci) and return the resulting S.

**Comment by simonvarey** [comment]
Fair enough, thanks for considering this.
